ARG ELK_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

# To view logs, visit:
# http://localhost:9200
# To see the available indices:
# http://localhost:9200/_cat/indices?v
# To view logs stored in the specific index 'logstash-2023.10.23-000001':
# http://localhost:9200/logstash-2023.10.23-000001/_search?pretty

# Note: Ensure that your ELK stack components (Elasticsearch, Logstash, Kibana) are appropriately secured.
# Open access can expose sensitive data. Always consider security best practices when deploying in a production environment.
