global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['docker-user-service-1:8080']

  - job_name: 'flight-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['docker-flight-service-1:8080']

  - job_name: 'airport-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['docker-airport-service-1:8080']

  - job_name: 'airplane-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['docker-airplane-service-1:8080']

  - job_name: 'reservation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['docker-reservation-service-1:8080']