# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - user-service
          - notification-service
          - flight-service
          - airport-service
          - airplane-service
          - admin-service
    steps:
      - name: Say Hello
        run: echo "Hello World"
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./${{ matrix.service }}/gradlew
      - name: Build with Gradle
        run: cd ./${{ matrix.service }} && ./gradlew build -x test

      # Snyk Integration
      - name: Install Snyk
        run: npm install -g snyk
      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Test
        run: snyk test --all-projects
      # - name: Snyk Monitor
      #   run: snyk monitor --all-projects

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ matrix.service }}-artifact
      #     path: |
      #       ./${{ matrix.service }}/build/libs/*.jar
